// The curated /school library's index — metadata only (the actual beat data
// lives in the `lessons` table, seeded by scripts/seedLessons.mts). Kept as a
// plain array in code, not a query, so the /school index page can list
// lessons in order without a round trip. Mirrors famousSongs.ts, but ordered
// as a stepwise curriculum (lessonNumber) instead of a flat list of songs.
export interface DrumLesson {
  slug: string;
  lessonNumber: number;
  title: string;
  teaches: string;
}

export const DRUM_LESSONS: DrumLesson[] = [
  { slug: "lesson-1-the-pulse", lessonNumber: 1, title: "Find the Pulse", teaches: "Steady quarter notes on the hi-hat." },
  { slug: "lesson-2-the-backbeat", lessonNumber: 2, title: "Add the Backbeat", teaches: "Snare on beats 2 and 4." },
  { slug: "lesson-3-the-kick", lessonNumber: 3, title: "Add the Kick", teaches: "Bass drum on beats 1 and 3 — the basic rock beat." },
  { slug: "lesson-4-eighth-note-hihat", lessonNumber: 4, title: "Eighth-Note Hi-Hat", teaches: "Doubling the hi-hat for a driving feel." },
  { slug: "lesson-5-syncopated-kick", lessonNumber: 5, title: "Syncopate the Kick", teaches: "Moving a kick hit onto the off-beat." },
  { slug: "lesson-6-fast-drive", lessonNumber: 6, title: "Fast Straight-Eighth Drive", teaches: "A driving, uptempo groove with the kick on every beat." },
  { slug: "lesson-7-open-hihat", lessonNumber: 7, title: "Open Hi-Hat Accents", teaches: "Opening and closing the hi-hat for a splashy accent." },
  { slug: "lesson-8-tom-fill", lessonNumber: 8, title: "Your First Fill: The Tom Run", teaches: "A one-bar fill that walks down the toms." },
  { slug: "lesson-9-eighth-fill", lessonNumber: 9, title: "Eighth-Note Fill", teaches: "Breaking just the last beat into a quick snare fill." },
  { slug: "lesson-10-put-it-together", lessonNumber: 10, title: "Put It Together", teaches: "Verse, chorus, and fills arranged into one song." },
  { slug: "lesson-11-sixteenth-note-hihat", lessonNumber: 11, title: "Sixteenth-Note Hi-Hat", teaches: "Subdividing the hi-hat into sixteenths for a smoother, busier feel." },
  { slug: "lesson-12-ghost-notes", lessonNumber: 12, title: "Ghost Notes", teaches: "Quiet snare hits between the backbeat, for texture instead of volume." },
  { slug: "lesson-13-train-beat", lessonNumber: 13, title: "The Train Beat", teaches: "A driving eighth-note pattern voiced on the snare, with the downbeat of each pair accented for a chugging feel." },
  { slug: "lesson-14-halftime-groove", lessonNumber: 14, title: "Halftime Groove", teaches: "Moving the snare to just beat 3 for a laid-back, spacious feel." },
  { slug: "lesson-15-double-time-feel", lessonNumber: 15, title: "Double-Time Feel", teaches: "The same basic rock beat, played fast enough to feel like a different gear." },
  { slug: "lesson-16-the-shuffle", lessonNumber: 16, title: "The Shuffle", teaches: "A swung, triplet-based hi-hat feel instead of straight time." },
  { slug: "lesson-17-funk-sixteenth-groove", lessonNumber: 17, title: "Funk Sixteenth Groove", teaches: "Syncopating the kick within a sixteenth-note grid, plus ghost notes." },
  { slug: "lesson-18-linear-fill", lessonNumber: 18, title: "Linear Fill", teaches: "A fill where no two limbs ever hit at the same instant, versus one that stacks hits together." },
  { slug: "lesson-19-sixteenth-note-fill", lessonNumber: 19, title: "Sixteenth-Note Fill", teaches: "Filling the last beat with a running sixteenth-note cascade instead of quarter notes." },
  { slug: "lesson-20-crash-into-the-groove", lessonNumber: 20, title: "Crash Into the Groove", teaches: "Using a pickup fill and a crash-plus-kick hit together to mark a new section." },
  { slug: "lesson-21-odd-grouping", lessonNumber: 21, title: "Odd Grouping: 3+3+2", teaches: "Splitting a bar of eighth notes into groups of 3+3+2 instead of four even beats." },
  { slug: "lesson-22-the-one-drop", lessonNumber: 22, title: "The One-Drop", teaches: "Landing the kick and snare together on beat 3 instead of spreading them across the bar." },
  { slug: "lesson-23-disco-four-on-the-floor", lessonNumber: 23, title: "Disco Four-on-the-Floor", teaches: "Kick on every beat, with the hi-hat opening on each off-beat for color." },
  { slug: "lesson-24-cross-stick-backbeat", lessonNumber: 24, title: "Cross-Stick Backbeat", teaches: "A quieter rimshot backbeat for a verse, opening up to full snare for the chorus." },
  { slug: "lesson-25-building-dynamics", lessonNumber: 25, title: "Building Dynamics: Verse to Chorus", teaches: "Leaving the snare out entirely in a sparse verse, so the chorus has somewhere to go." },
  { slug: "lesson-26-the-big-fill", lessonNumber: 26, title: "The Big Fill", teaches: "A fill that takes over the entire bar, for a bigger moment than a one-beat tom run." },
  { slug: "lesson-27-sixteenth-note-kick", lessonNumber: 27, title: "Sixteenth-Note Kick Pattern", teaches: "A funk/hip-hop-style kick pattern built from sixteenth-note syncopation." },
  { slug: "lesson-28-odd-meter-groove", lessonNumber: 28, title: "7-Beat Groove", teaches: "An asymmetric 3+2+2 grouping across a 7-beat measure, instead of four even beats." },
  { slug: "lesson-29-full-arrangement", lessonNumber: 29, title: "Full Arrangement: Verse, Chorus, Fills", teaches: "Combining a halftime verse, a driving chorus, and two fills into one arranged song." },
  { slug: "lesson-30-graduation", lessonNumber: 30, title: "A Song of Your Own", teaches: "Verse, chorus, and bridge grooves plus a fill — everything from this course, in one song." },
  { slug: "lesson-31-paradiddle-groove", lessonNumber: 31, title: "Paradiddle Groove", teaches: "Adapting a sticking pattern (RLRR LRLL) onto hi-hat and snare instead of two hands." },
  { slug: "lesson-32-half-time-shuffle", lessonNumber: 32, title: "Half-Time Shuffle", teaches: "Combining the shuffle feel with a halftime backbeat and a ghost note, all at once." },
  { slug: "lesson-33-displaced-backbeat", lessonNumber: 33, title: "Displaced Backbeat", teaches: "Moving the snare off the downbeat entirely, onto the 'and' of 2 and 4." },
  { slug: "lesson-34-five-four-groove", lessonNumber: 34, title: "5/4 Groove", teaches: "A 5-beat measure grouped 3+2, instead of the usual 4." },
  { slug: "lesson-35-six-eight-groove", lessonNumber: 35, title: "6/8 Compound Groove", teaches: "A 6-beat measure felt as two big pulses of three, not six even beats." },
  { slug: "lesson-36-sixteenth-kick-ostinato", lessonNumber: 36, title: "Sixteenth-Note Kick Ostinato", teaches: "A continuous running sixteenth-note kick pattern underneath the groove, for a heavy, driving feel." },
  { slug: "lesson-37-ride-cymbal-groove", lessonNumber: 37, title: "Ride Cymbal Groove", teaches: "Moving timekeeping from the hi-hat to the ride cymbal for a more open, washy sound." },
  { slug: "lesson-38-hemiola", lessonNumber: 38, title: "Hemiola: Grouping in 3s Over a 4-Beat Bar", teaches: "Accenting every third eighth note, so a steady 4-beat bar briefly feels like it's in 3." },
  { slug: "lesson-39-groove-from-a-fill", lessonNumber: 39, title: "Building a Groove From a Fill", teaches: "Taking the Lesson 8 tom run's shape and turning it into a sustained groove instead of a one-bar detour." },
  { slug: "lesson-40-samba-influenced-feel", lessonNumber: 40, title: "Samba-Influenced Feel", teaches: "A two-beat surdo-style kick pattern (downbeat plus a syncopated push) under steady eighths." },
  { slug: "lesson-41-songo-influenced-groove", lessonNumber: 41, title: "Songo-Influenced Groove", teaches: "A different kick/snare syncopation than the samba feel, both built from the same eighth-note grid." },
  { slug: "lesson-42-afrobeat-influenced-groove", lessonNumber: 42, title: "Afrobeat-Influenced Groove", teaches: "A steady sixteenth-note hi-hat with a syncopated kick and a cross-stick answering on the off-beats." },
  { slug: "lesson-43-second-line-groove", lessonNumber: 43, title: "Second-Line Groove", teaches: "A bouncy, syncopated kick-and-snare conversation instead of a fixed backbeat." },
  { slug: "lesson-44-blast-beat-intro", lessonNumber: 44, title: "Blast Beat Intro", teaches: "Kick, snare, and hi-hat all hitting together on every eighth note, as fast as you can hold it." },
  { slug: "lesson-45-polyrhythm-4-over-3", lessonNumber: 45, title: "Polyrhythm: Grouping in 3s Over Sixteenths", teaches: "Accenting every third sixteenth note across a steady 4-beat bar, for a rolling cross-rhythm feel." },
  { slug: "lesson-46-odd-time-fill", lessonNumber: 46, title: "Odd-Time Fill", teaches: "A fill built to span a 5-beat measure, matching the 5/4 groove from Lesson 34." },
  { slug: "lesson-47-dynamics-across-the-groove", lessonNumber: 47, title: "Dynamics Across the Whole Groove", teaches: "Accents and ghost notes on the kick and hi-hat too, not just the snare." },
  { slug: "lesson-48-building-an-intro", lessonNumber: 48, title: "Building an Intro", teaches: "A crash-and-tom pickup that leads into the groove, the way a lot of songs actually start." },
  { slug: "lesson-49-full-arrangement-advanced", lessonNumber: 49, title: "Full Arrangement: Advanced", teaches: "A shuffle verse, a displaced-backbeat chorus, and two fills arranged into one song." },
  { slug: "lesson-50-graduation-two", lessonNumber: 50, title: "Fifty Lessons In", teaches: "A paradiddle-based verse, a samba-influenced bridge, a driving chorus, and a fill — the advanced half, in one song." },
  { slug: "lesson-51-offbeat-skank-groove", lessonNumber: 51, title: "Offbeat Skank Groove", teaches: "A hi-hat pattern voiced entirely on the off-beat 'and' of each beat, with the kick landing alone on beat 3." },
  { slug: "lesson-52-jazz-ride-pattern", lessonNumber: 52, title: "Jazz Ride Pattern", teaches: "A swung ride-cymbal ostinato (the 'spang-a-lang' shape) with soft snare comping underneath instead of a fixed backbeat." },
  { slug: "lesson-53-waltz-time", lessonNumber: 53, title: "Waltz Time: Three-Beat Feel", teaches: "A 3-beat measure with the bass drum on beat 1 and the hi-hat keeping a gentle three-count, instead of grouping in four." },
  { slug: "lesson-54-gospel-chop-groove", lessonNumber: 54, title: "Gospel Chop Groove", teaches: "A busy, syncopated sixteenth-note kick-and-snare conversation with the hi-hat holding steady eighths on top." },
  { slug: "lesson-55-alternating-double-kick", lessonNumber: 55, title: "Alternating Double-Kick Feel", teaches: "A continuous sixteenth-note kick pattern with alternating accents, the way a double-bass-pedal player alternates emphasis between feet." },
  { slug: "lesson-56-breakbeat-groove", lessonNumber: 56, title: "Breakbeat Groove", teaches: "A fast, syncopated kick-and-snare breakbeat pattern lifted off the sixteenth-note grid instead of landing on the obvious beats." },
  { slug: "lesson-57-clave-influenced-groove", lessonNumber: 57, title: "Clave-Influenced Groove", teaches: "A kick-and-rimshot pattern echoing a generic three-against-two clave shape, spread across the bar instead of a straight backbeat." },
  { slug: "lesson-58-funk-ghost-cascade", lessonNumber: 58, title: "Funk Ghost Cascade", teaches: "Multiple ghost notes packed into a single beat on the snare, filling space between sparse kick hits." },
  { slug: "lesson-59-dynamic-crescendo-fill", lessonNumber: 59, title: "Dynamic Crescendo Fill", teaches: "A one-bar snare fill that builds from ghost notes to full accents across the bar instead of staying one volume." },
  { slug: "lesson-60-full-arrangement-groove-toolkit", lessonNumber: 60, title: "Full Arrangement: Groove Toolkit", teaches: "Combining a reggae-influenced verse, a gospel-chop chorus, and two contrasting fills into one arranged song." },
  { slug: "lesson-61-triplet-fill", lessonNumber: 61, title: "Triplet Fill", teaches: "A one-bar fill built entirely from triplet subdivisions instead of straight sixteenths." },
  { slug: "lesson-62-cross-rhythm-fill", lessonNumber: 62, title: "Cross-Rhythm Fill", teaches: "A fill that accents every third eighth note across a 4-beat bar, carrying the hemiola idea from Lesson 38 into a fill instead of a groove." },
  { slug: "lesson-63-five-four-groove-two-three", lessonNumber: 63, title: "5/4 Groove: 2+3", teaches: "The same 5-beat measure as Lesson 34, regrouped 2+3 instead of 3+2 — a different feel from the same meter." },
  { slug: "lesson-64-odd-meter-ghost-notes", lessonNumber: 64, title: "Odd-Meter Ghost Notes", teaches: "A 7-beat measure (grouped 2+2+3) with ghost notes woven between the backbeat hits, combining odd meter and dynamics." },
  { slug: "lesson-65-rudiment-style-march", lessonNumber: 65, title: "Rudiment-Style March", teaches: "A snare pattern using a ghost sixteenth right before each accent to approximate a flam, over a steady quarter-note bass drum march." },
  { slug: "lesson-66-cut-time-punk-drive", lessonNumber: 66, title: "Cut-Time Punk Drive", teaches: "A very fast, stripped-down groove with the kick landing on every quarter note and a pushed snare accent into beat 4 — punk and hardcore's forward drive." },
  { slug: "lesson-67-displaced-hihat-accents", lessonNumber: 67, title: "Displaced Hi-Hat Accents", teaches: "Accenting the hi-hat on the off-beats instead of the downbeats, while the kick and snare stay put — shifting where the ear locks in without moving the backbeat." },
  { slug: "lesson-68-tom-voiced-groove", lessonNumber: 68, title: "Tom-Voiced Groove", teaches: "A groove where the toms carry the main rhythm instead of hi-hat and snare, for a tribal, low-end-heavy feel." },
  { slug: "lesson-69-sixteenth-note-hihat-opens", lessonNumber: 69, title: "Sixteenth-Note Hi-Hat Opens", teaches: "Opening the hi-hat on select sixteenth-note partials instead of just the eighth-note off-beats, for a busier splash pattern." },
  { slug: "lesson-70-full-arrangement-advanced-textures", lessonNumber: 70, title: "Full Arrangement: Advanced Textures", teaches: "Combining a displaced-hi-hat verse, a gospel-chop chorus, and a triplet fill into one arranged song." },
  { slug: "lesson-71-half-time-power-ballad", lessonNumber: 71, title: "Half-Time Power Ballad", teaches: "A slow half-time groove with a heavily accented backbeat and a sustained crash, the arena-ballad feel." },
  { slug: "lesson-72-funk-groove-hihat-splashes", lessonNumber: 72, title: "Funk Groove with Hi-Hat Splashes", teaches: "Layering open hi-hat splashes onto a syncopated sixteenth-note funk kick pattern." },
  { slug: "lesson-73-alternating-blast-beat", lessonNumber: 73, title: "Alternating Blast Beat", teaches: "A blast beat where kick and snare alternate every eighth note instead of hitting together, for a different kind of relentless drive." },
  { slug: "lesson-74-bossa-influenced-feel", lessonNumber: 74, title: "Bossa-Influenced Feel", teaches: "A relaxed Latin-adjacent feel with a steady eighth-note hi-hat and a syncopated rimshot pattern, quieter than the samba and songo feels." },
  { slug: "lesson-75-ride-cymbal-dynamics", lessonNumber: 75, title: "Ride Cymbal Dynamics", teaches: "Accenting select ride-cymbal hits while keeping the rest at normal volume, the way a bell accent cuts through a ride pattern." },
  { slug: "lesson-76-full-bar-linear-fill", lessonNumber: 76, title: "Full-Bar Linear Fill", teaches: "A fill spanning the entire bar where kick, snare, and toms trade sixteenth notes without ever overlapping." },
  { slug: "lesson-77-syncopated-ride-groove", lessonNumber: 77, title: "Syncopated Ride Groove", teaches: "A ride-cymbal pattern with the off-beat 'and' dropped out here and there, instead of playing every eighth note evenly." },
  { slug: "lesson-78-shuffle-in-five", lessonNumber: 78, title: "Shuffle in Five", teaches: "The shuffle's swung triplet hi-hat feel, now stretched across a 5-beat measure instead of 4." },
  { slug: "lesson-79-groove-that-builds", lessonNumber: 79, title: "Groove That Builds Within the Bar", teaches: "A single groove where the hi-hat itself ramps from ghost to accent across the bar, so the intensity builds without the pattern changing." },
  { slug: "lesson-80-full-arrangement-grooves-in-motion", lessonNumber: 80, title: "Full Arrangement: Grooves in Motion", teaches: "A half-time-ballad verse, a funk chorus with hi-hat splashes, and two fills — the busiest arrangement yet." },
  { slug: "lesson-81-three-over-two-kick", lessonNumber: 81, title: "Three-Over-Two Kick Pattern", teaches: "A kick pattern that lands every dotted quarter note against a steady straight pulse, a simple polyrhythm you can feel in the feet." },
  { slug: "lesson-82-six-eight-bell-pattern", lessonNumber: 82, title: "6/8 Bell Pattern Feel", teaches: "A 6-beat groove with a rimshot outlining a bell-pattern rhythm underneath a steady pulse." },
  { slug: "lesson-83-snare-led-sixteenth-groove", lessonNumber: 83, title: "Snare-Led Sixteenth Groove", teaches: "A continuous sixteenth-note snare ostinato with the kick only accenting select hits underneath, flipping which instrument leads the groove." },
  { slug: "lesson-84-inverted-accent-groove", lessonNumber: 84, title: "Inverted Accent Groove", teaches: "Accenting the off-beats and ghosting the downbeats on the hi-hat — the reverse of where accents usually land." },
  { slug: "lesson-85-shuffle-feel-fill", lessonNumber: 85, title: "Shuffle-Feel Fill", teaches: "A tom fill built from the shuffle's triplet skip shape instead of straight sixteenths." },
  { slug: "lesson-86-kick-ostinato-meets-ghost-snare", lessonNumber: 86, title: "Kick Ostinato Meets Ghost Snare", teaches: "Combining the continuous sixteenth-note kick ostinato from Lesson 36 with a dense ghost-note snare pattern underneath a steady hi-hat." },
  { slug: "lesson-87-dotted-eighth-loping-feel", lessonNumber: 87, title: "Dotted-Eighth Loping Feel", teaches: "A hi-hat pattern built from dotted-eighth-plus-sixteenth cells instead of straight or swung eighths, for a loping, uneven pulse." },
  { slug: "lesson-88-sixteenth-cross-stick-groove", lessonNumber: 88, title: "Sixteenth-Note Cross-Stick Groove", teaches: "Moving the quiet cross-stick backbeat from Lesson 24 onto a syncopated sixteenth-note grid instead of a plain quarter-note backbeat." },
  { slug: "lesson-89-call-and-response-fill", lessonNumber: 89, title: "Call-and-Response Fill", teaches: "A fill built as a short snare phrase answered by tom phrases, trading back and forth within the bar." },
  { slug: "lesson-90-full-arrangement-polyrhythms-and-ghosts", lessonNumber: 90, title: "Full Arrangement: Polyrhythms and Ghosts", teaches: "A polyrhythmic-kick verse, an inverted-accent chorus, and two fills arranged into one song." },
  { slug: "lesson-91-half-time-double-kick-groove", lessonNumber: 91, title: "Half-Time Double-Kick Groove", teaches: "A half-time backbeat with a continuous sixteenth-note double-kick pattern underneath, instead of a sparse kick." },
  { slug: "lesson-92-breakbeat-in-five", lessonNumber: 92, title: "Breakbeat in Five", teaches: "The syncopated breakbeat feel from Lesson 56, now fit into a 5-beat measure instead of straight 4/4." },
  { slug: "lesson-93-inverted-paradiddle-groove", lessonNumber: 93, title: "Inverted Paradiddle Groove", teaches: "The paradiddle sticking pattern from Lesson 31, with the two voices swapped — landing the accents in different spots than before." },
  { slug: "lesson-94-independent-limb-dynamics", lessonNumber: 94, title: "Independent Limb Dynamics", teaches: "Accenting the kick at the same instant the snare plays a ghost note, so each limb carries its own dynamic level independently." },
  { slug: "lesson-95-full-triplet-groove", lessonNumber: 95, title: "Full Triplet Groove", teaches: "A groove where kick, snare, and hi-hat all sit on the triplet grid together, not just the hi-hat like the shuffle." },
  { slug: "lesson-96-full-kit-crescendo-fill", lessonNumber: 96, title: "Full-Kit Crescendo Fill", teaches: "A fill where the hi-hat, kick, and snare all ramp from ghost to accent together, for a big buildup into the next section." },
  { slug: "lesson-97-latin-influenced-ghost-groove", lessonNumber: 97, title: "Latin-Influenced Ghost Groove", teaches: "Layering ghost notes onto the clave-influenced kick-and-rimshot pattern from Lesson 57." },
  { slug: "lesson-98-odd-meter-triplet-fill", lessonNumber: 98, title: "Odd-Meter Triplet Fill", teaches: "A fill spanning a 7-beat measure built from triplet subdivisions, combining odd meter and triplet phrasing." },
  { slug: "lesson-99-full-arrangement-the-home-stretch", lessonNumber: 99, title: "Full Arrangement: The Home Stretch", teaches: "A polyrhythmic-kick verse, a half-time double-kick chorus, and two fills — one last full arrangement before the final song." },
  { slug: "lesson-100-graduation", lessonNumber: 100, title: "Graduation: Everything You've Learned", teaches: "A full song combining sixteenth-note ghost/accent dynamics, a driving double-kick chorus, a 7-beat odd-meter bridge, and a full-kit crescendo fill — the whole hundred-lesson course, in one song." },
];
